In [30]:
import pandas as pd
import numpy as np

df = pd.read_csv("database.csv", low_memory=False)

df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,000001,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,January,1.0,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0.0,0.0,FBI
1,000002,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,1.0,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0.0,0.0,FBI
2,000003,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,2.0,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0.0,0.0,FBI
3,000004,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,1.0,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0.0,0.0,FBI
4,000005,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,2.0,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0.0,1.0,FBI

In [31]:
print(df.shape)
print(df.columns)

(638455, 24)
Index(['Record ID', 'Agency Code', 'Agency Name', 'Agency Type', 'City',
       'State', 'Year', 'Month', 'Incident', 'Crime Type', 'Crime Solved',
       'Victim Sex', 'Victim Age', 'Victim Race', 'Victim Ethnicity',
       'Perpetrator Sex', 'Perpetrator Age', 'Perpetrator Race',
       'Perpetrator Ethnicity', 'Relationship', 'Weapon', 'Victim Count',
       'Perpetrator Count', 'Record Source'],
      dtype='str')

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 638455 entries, 0 to 638454
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Record ID              638455 non-null  str
 1   Agency Code            638454 non-null  str
 2   Agency Name            638454 non-null  str
 3   Agency Type            638454 non-null  str
 4   City                   638454 non-null  str
 5   State                  638454 non-null  str
 6   Year                   638454 non-null  float64
 7   Month                  638454 non-null  str
 8   Incident               638454 non-null  float64
 9   Crime Type             638454 non-null  str
 10  Crime Solved           638454 non-null  str
 11  Victim Sex             638454 non-null  str
 12  Victim Age             638454 non-null  float64
 13  Victim Race            638454 non-null  str
 14  Victim Ethnicity       638454 non-null  str
 15  Perpetrator Sex        638454 non-null  str
 16  Perpetrator Age        638454 non-null  str
 17  Perpetrator Race       638454 non-null  str
 18  Perpetrator Ethnicity  638454 non-null  str
 19  Relationship           638454 non-null  str
 20  Weapon                 638454 non-null  str
 21  Victim Count           638454 non-null  float64
 22  Perpetrator Count      638454 non-null  float64
 23  Record Source          638454 non-null  str
dtypes: float64(5), str(19)
memory usage: 116.9 MB

In [33]:
df.describe(include='all')

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
count,638455,638454,638454,638454,638454,638454,638454.000000,638454,638454.000000,638454,...,638454,638454,638454,638454,638454,638454,638454,638454.000000,638454.000000,638454
unique,638455,12003,9216,7,1782,51,NaN,12,NaN,2,...,3,3,101,5,3,28,16,NaN,NaN,2
top,000001,NY03030,New York,Municipal Police,Los Angeles,California,NaN,July,NaN,Murder or Manslaughter,...,Unknown,Male,0,White,Unknown,Unknown,Handgun,NaN,NaN,FBI
freq,1,38416,38416,493026,44511,99783,NaN,58696,NaN,629338,...,368303,399541,216327,218243,446410,273013,317484,NaN,NaN,616647
mean,NaN,NaN,NaN,NaN,NaN,NaN,1995.801102,NaN,22.967924,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.123334,0.185224,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.927693,NaN,92.149821,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.537733,0.585496,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1980.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1987.000000,NaN,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1995.000000,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2004.000000,NaN,10.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2014.000000,NaN,999.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,NaN

In [34]:
df.isnull().sum().sort_values(ascending=False)

Agency Code              1
Agency Name              1
Agency Type              1
City                     1
Year                     1
State                    1
Month                    1
Incident                 1
Perpetrator Age          1
Crime Type               1
Crime Solved             1
Victim Sex               1
Victim Age               1
Victim Race              1
Victim Ethnicity         1
Perpetrator Sex          1
Weapon                   1
Perpetrator Race         1
Perpetrator Ethnicity    1
Relationship             1
Perpetrator Count        1
Victim Count             1
Record Source            1
Record ID                0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df['State'].unique()

<StringArray>
[              'Alaska',              'Alabama',             'Arkansas',
              'Arizona',           'California',             'Colorado',
          'Connecticut', 'District of Columbia',             'Delaware',
              'Florida',              'Georgia',               'Hawaii',
                 'Iowa',                'Idaho',             'Illinois',
              'Indiana',               'Kansas',             'Kentucky',
            'Louisiana',        'Massachusetts',             'Maryland',
                'Maine',             'Michigan',            'Minnesota',
             'Missouri',          'Mississippi',              'Montana',
             'Nebraska',       'North Carolina',         'North Dakota',
        'New Hampshire',           'New Jersey',           'New Mexico',
               'Nevada',             'New York',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
        'Rhodes Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
             'Virginia',              'Vermont',           'Washington',
            'Wisconsin',        'West Virginia',              'Wyoming',
                    nan]
Length: 52, dtype: str

In [37]:
df['Weapon'].unique()

<StringArray>
[ 'Blunt Object', 'Strangulation',       'Unknown',         'Rifle',
         'Knife',       'Firearm',       'Shotgun',          'Fall',
       'Handgun',      'Drowning',   'Suffocation',    'Explosives',
          'Fire',         'Drugs',           'Gun',        'Poison',
             nan]
Length: 17, dtype: str

In [38]:
df['Relationship'].unique()

<StringArray>
[        'Acquaintance',              'Unknown',                 'Wife',
             'Stranger',           'Girlfriend',           'Ex-Husband',
              'Brother',         'Stepdaughter',              'Husband',
               'Sister',               'Friend',               'Family',
             'Neighbor',               'Father',               'In-Law',
                  'Son',              'Ex-Wife',            'Boyfriend',
               'Mother',   'Common-Law Husband',      'Common-Law Wife',
           'Stepfather',              'Stepson',           'Stepmother',
             'Daughter', 'Boyfriend/Girlfriend',             'Employer',
             'Employee',                    nan]
Length: 29, dtype: str

In [39]:
df.replace("Unknown", np.nan, inplace=True)

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,000001,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,January,1.0,Murder or Manslaughter,...,NaN,Male,15,Native American/Alaska Native,NaN,Acquaintance,Blunt Object,0.0,0.0,FBI
1,000002,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,1.0,Murder or Manslaughter,...,NaN,Male,42,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI
2,000003,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,2.0,Murder or Manslaughter,...,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,0.0,FBI
3,000004,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,1.0,Murder or Manslaughter,...,NaN,Male,42,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI
4,000005,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,2.0,Murder or Manslaughter,...,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,1.0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014.0,June,1.0,Murder or Manslaughter,...,NaN,Male,57,White,NaN,Acquaintance,Handgun,0.0,0.0,FBI
638451,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014.0,September,1.0,Murder or Manslaughter,...,NaN,Female,22,Asian/Pacific Islander,NaN,Daughter,Suffocation,0.0,0.0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014.0,December,1.0,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0.0,1.0,FBI
638453,638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014.0,September,1.0,Murder or Manslaughter,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0.0,1.0,FBI
638454,.gitignore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df.isnull().sum().sort_values(ascending=False)

Perpetrator Ethnicity    446411
Victim Ethnicity         368304
Relationship             273014
Perpetrator Race         196048
Perpetrator Sex          190366
Weapon                    33193
Victim Race                6677
Victim Sex                  985
Agency Name                  48
Victim Age                    1
State                         1
Month                         1
City                          1
Agency Type                   1
Agency Code                   1
Year                          1
Perpetrator Age               1
Incident                      1
Crime Type                    1
Crime Solved                  1
Perpetrator Count             1
Victim Count                  1
Record Source                 1
Record ID                     0
dtype: int64

In [42]:
df['Victim Sex'].fillna("Unknown", inplace=True)
df['Perpetrator Sex'].fillna("Unknown", inplace=True)
df['Weapon'].fillna("Unknown", inplace=True)
df['Relationship'].fillna("Unknown", inplace=True)

C:\Users\anany\AppData\Local\Temp\ipykernel_6452\3360752814.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Victim Sex'].fillna("Unknown", inplace=True)
C:\Users\anany\AppData\Local\Temp\ipykernel_6452\3360752814.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Perpetrator Sex'].fillna("Unknown", inplace=True)
C:\Users\anany\AppData\Local\Temp\ipykernel_6452\3360752814.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Weapon'].fillna("Unknown", inplace=True)
C:\Users\anany\AppData\Local\Temp\ipykernel_6452\3360752814.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Relationship'].fillna("Unknown", inplace=True)

0         Acquaintance
1         Acquaintance
2              Unknown
3         Acquaintance
4              Unknown
              ...
638450    Acquaintance
638451        Daughter
638452        Stranger
638453        Daughter
638454         Unknown
Name: Relationship, Length: 638455, dtype: str

In [44]:
def clean_weapon(x):
    if pd.isnull(x):
        return "Unknown"
    x = x.lower()
    if any(k in x for k in ["gun", "firearm", "rifle", "shotgun"]):
        return "Firearm"
    elif "knife" in x:
        return "Sharp Object"
    elif "blunt" in x:
        return "Blunt Object"
    else:
        return "Other"

df['Weapon_Group'] = df['Weapon'].apply(clean_weapon)

In [46]:
def clean_relationship(x):
    if pd.isnull(x):
        return "Unknown"
    
    x = x.lower()
    
    if any(k in x for k in ["wife","husband","girlfriend","boyfriend"]):
        return "Partner"
    elif any(k in x for k in ["father","mother","son","daughter"]):
        return "Family"
    elif any(k in x for k in ["brother","sister"]):
        return "Sibling"
    elif any(k in x for k in ["friend","neighbor","acquaintance"]):
        return "Known"
    elif "stranger" in x:
        return "Stranger"
    else:
        return "Other"

df['Relationship_Group'] = df['Relationship'].apply(clean_relationship)

In [47]:
df[['Victim Age', 'Perpetrator Age']].describe()

          Victim Age
count  638454.000000
mean       35.033512
std        41.628306
min         0.000000
25%        22.000000
50%        30.000000
75%        42.000000
max       998.000000

In [50]:
#to convert into numeric as there are string in age columns

df['Victim Age'] = pd.to_numeric(df['Victim Age'], errors='coerce') 
df['Perpetrator Age'] = pd.to_numeric(df['Perpetrator Age'], errors='coerce')

In [51]:
df.loc[df['Victim Age'] <= 0, 'Victim Age'] = np.nan
df.loc[df['Perpetrator Age'] <= 0, 'Perpetrator Age'] = np.nan

In [52]:
df[['Victim Age', 'Perpetrator Age']].describe()

          Victim Age  Perpetrator Age
count  630010.000000    422126.000000
mean       35.503065        30.737474
std        41.706972        12.797424
min         1.000000         1.000000
25%        22.000000        21.000000
50%        30.000000        27.000000
75%        42.000000        37.000000
max       998.000000        99.000000

In [55]:
df.loc[df['Victim Age'] > 100, 'Victim Age'] = np.nan

In [56]:
df['Perpetrator_Age_Available'] = df['Perpetrator Age'].notnull()

In [57]:
df[['Victim Age', 'Perpetrator Age']].describe()

          Victim Age  Perpetrator Age
count  629036.000000    422126.000000
mean       34.012734        30.737474
std        17.478623        12.797424
min         1.000000         1.000000
25%        22.000000        21.000000
50%        30.000000        27.000000
75%        42.000000        37.000000
max        99.000000        99.000000

In [59]:
df.loc[df['Perpetrator Age'] > 100, 'Perpetrator Age'] = np.nan

In [60]:
df[df['Victim Age'] > 100]

Empty DataFrame
Columns: [Record ID, Agency Code, Agency Name, Agency Type, City, State, Year, Month, Incident, Crime Type, Crime Solved, Victim Sex, Victim Age, Victim Race, Victim Ethnicity, Perpetrator Sex, Perpetrator Age, Perpetrator Race, Perpetrator Ethnicity, Relationship, Weapon, Victim Count, Perpetrator Count, Record Source, Weapon_Group, Relationship_Group, Perpetrator_Age_Available]
Index: []

[0 rows x 27 columns]

In [61]:
df[df['Perpetrator Age'] > 100]

Empty DataFrame
Columns: [Record ID, Agency Code, Agency Name, Agency Type, City, State, Year, Month, Incident, Crime Type, Crime Solved, Victim Sex, Victim Age, Victim Race, Victim Ethnicity, Perpetrator Sex, Perpetrator Age, Perpetrator Race, Perpetrator Ethnicity, Relationship, Weapon, Victim Count, Perpetrator Count, Record Source, Weapon_Group, Relationship_Group, Perpetrator_Age_Available]
Index: []

[0 rows x 27 columns]

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 638455 entries, 0 to 638454
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Record ID                  638455 non-null  str
 1   Agency Code                638454 non-null  str
 2   Agency Name                638407 non-null  str
 3   Agency Type                638454 non-null  str
 4   City                       638454 non-null  str
 5   State                      638454 non-null  str
 6   Year                       638454 non-null  float64
 7   Month                      638454 non-null  str
 8   Incident                   638454 non-null  float64
 9   Crime Type                 638454 non-null  str
 10  Crime Solved               638454 non-null  str
 11  Victim Sex                 637470 non-null  str
 12  Victim Age                 629036 non-null  float64
 13  Victim Race                631778 non-null  str
 14  Victim Ethnicity           270151 non-null  str
 15  Perpetrator Sex            448089 non-null  str
 16  Perpetrator Age            422126 non-null  float64
 17  Perpetrator Race           442407 non-null  str
 18  Perpetrator Ethnicity      192044 non-null  str
 19  Relationship               365441 non-null  str
 20  Weapon                     605262 non-null  str
 21  Victim Count               638454 non-null  float64
 22  Perpetrator Count          638454 non-null  float64
 23  Record Source              638454 non-null  str
 24  Weapon_Group               638455 non-null  str
 25  Relationship_Group         638455 non-null  str
 26  Perpetrator_Age_Available  638455 non-null  bool
dtypes: bool(1), float64(6), str(20)
memory usage: 127.3 MB

In [64]:
df.isnull().sum()

Record ID                         0
Agency Code                       1
Agency Name                      48
Agency Type                       1
City                              1
State                             1
Year                              1
Month                             1
Incident                          1
Crime Type                        1
Crime Solved                      1
Victim Sex                      985
Victim Age                     9419
Victim Race                    6677
Victim Ethnicity             368304
Perpetrator Sex              190366
Perpetrator Age              216329
Perpetrator Race             196048
Perpetrator Ethnicity        446411
Relationship                 273014
Weapon                        33193
Victim Count                      1
Perpetrator Count                 1
Record Source                     1
Weapon_Group                      0
Relationship_Group                0
Perpetrator_Age_Available         0
dtype: int64

In [73]:
df.head(15)
#The ‘Incident’ column represents a unique homicide case identifier within a given location and time period. Multiple records may belong to the same incident, representing multiple victims or perpetrators involved in that case.

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source,Weapon_Group,Relationship_Group,Perpetrator_Age_Available
0,000001,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,January,1.0,Murder or Manslaughter,...,Native American/Alaska Native,NaN,Acquaintance,Blunt Object,0.0,0.0,FBI,Blunt Object,Known,True
1,000002,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI,Other,Known,True
2,000003,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,0.0,FBI,Unknown,Unknown,False
3,000004,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI,Other,Known,True
4,000005,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,1.0,FBI,Unknown,Unknown,False
5,000006,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,May,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Rifle,0.0,0.0,FBI,Firearm,Known,True
6,000007,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,May,2.0,Murder or Manslaughter,...,Black,NaN,Wife,Knife,0.0,0.0,FBI,Sharp Object,Partner,True
7,000008,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,June,1.0,Murder or Manslaughter,...,White,NaN,Wife,Knife,0.0,0.0,FBI,Sharp Object,Partner,True
8,000009,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,June,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,Firearm,0.0,0.0,FBI,Firearm,Unknown,False
9,000010,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,June,3.0,Murder or Manslaughter,...,NaN,NaN,NaN,Firearm,0.0,1.0,FBI,Firearm,Unknown,True
10,000011,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,July,1.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,1.0,FBI,Unknown,Unknown,False
11,000012,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,July,2.0,Murder or Manslaughter,...,White,NaN,Stranger,Shotgun,0.0,0.0,FBI,Firearm,Stranger,True
12,000013,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,July,3.0,Murder or Manslaughter,...,Black,NaN,Girlfriend,Blunt Object,0.0,0.0,FBI,Blunt Object,Partner,True
13,000014,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,August,1.0,Murder or Manslaughter,...,White,NaN,NaN,Fall,0.0,0.0,FBI,Other,Unknown,True
14,000015,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,August,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,Handgun,0.0,0.0,FBI,Firearm,Unknown,False

In [74]:
total_incidents = df[['Year', 'Month', 'City', 'Incident']].drop_duplicates().shape[0]
total_incidents

478693

In [75]:
incidents_per_year = df.groupby('Year')['Incident'].nunique()
incidents_per_year

Year
1980.0     239
1981.0     180
1982.0     169
1983.0     213
1984.0     193
1985.0     142
1986.0     158
1987.0     201
1988.0     210
1989.0     210
1990.0     208
1991.0     216
1992.0     221
1993.0     186
1994.0     161
1995.0     136
1996.0     114
1997.0     310
1998.0      75
1999.0      75
2000.0     815
2001.0     927
2002.0     960
2003.0     976
2004.0    1000
2005.0     960
2006.0    1000
2007.0    1000
2008.0    1000
2009.0    1000
2010.0    1000
2011.0    1000
2012.0    1000
2013.0    1000
2014.0    1000
Name: Incident, dtype: int64

### The dataset contains multiple records per incident, representing multiple victims or perpetrators. Therefore, counting rows overestimates the number of crimes. Using unique incident counts provides a more accurate measure of crime occurrences.

##### Post-2004 data appears capped at 1000 incidents per year, indicating a limitation in the dataset.

In [84]:
df[df['Year'] < 2004]

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source,Weapon_Group,Relationship_Group,Perpetrator_Age_Available
0,000001,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,January,1.0,Murder or Manslaughter,...,Native American/Alaska Native,NaN,Acquaintance,Blunt Object,0.0,0.0,FBI,Blunt Object,Known,True
1,000002,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI,Other,Known,True
2,000003,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,0.0,FBI,Unknown,Unknown,False
3,000004,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI,Other,Known,True
4,000005,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,1.0,FBI,Unknown,Unknown,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465681,465682,WY01301,Casper,Municipal Police,Natrona,Wyoming,2003.0,August,1.0,Murder or Manslaughter,...,White,NaN,Son,Blunt Object,0.0,0.0,FBI,Blunt Object,Family,True
465682,465683,WY01301,Casper,Municipal Police,Natrona,Wyoming,2003.0,September,1.0,Murder or Manslaughter,...,White,NaN,Wife,Blunt Object,0.0,0.0,FBI,Blunt Object,Partner,True
465683,465684,WY01304,Evansville,Municipal Police,Natrona,Wyoming,2003.0,July,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Blunt Object,0.0,0.0,FBI,Blunt Object,Known,True
465684,465685,WY01900,Sweetwater,Sheriff,Sweetwater,Wyoming,2003.0,January,1.0,Murder or Manslaughter,...,White,NaN,In-Law,Rifle,0.0,0.0,FBI,Firearm,Other,True
465685,465686,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2003.0,July,1.0,Murder or Manslaughter,...,White,NaN,NaN,Suffocation,0.0,0.0,FBI,Other,Unknown,True

##### To ensure accurate trend analysis, only data prior to 2004 was considered, as later years show a consistent cap at 1000 incidents, indicating dataset truncation.

In [87]:
#for time analysis 

df_trend = df[df['Year'] < 2004]
df_trend

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source,Weapon_Group,Relationship_Group,Perpetrator_Age_Available
0,000001,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,January,1.0,Murder or Manslaughter,...,Native American/Alaska Native,NaN,Acquaintance,Blunt Object,0.0,0.0,FBI,Blunt Object,Known,True
1,000002,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI,Other,Known,True
2,000003,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,0.0,FBI,Unknown,Unknown,False
3,000004,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Strangulation,0.0,0.0,FBI,Other,Known,True
4,000005,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,2.0,Murder or Manslaughter,...,NaN,NaN,NaN,NaN,0.0,1.0,FBI,Unknown,Unknown,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465681,465682,WY01301,Casper,Municipal Police,Natrona,Wyoming,2003.0,August,1.0,Murder or Manslaughter,...,White,NaN,Son,Blunt Object,0.0,0.0,FBI,Blunt Object,Family,True
465682,465683,WY01301,Casper,Municipal Police,Natrona,Wyoming,2003.0,September,1.0,Murder or Manslaughter,...,White,NaN,Wife,Blunt Object,0.0,0.0,FBI,Blunt Object,Partner,True
465683,465684,WY01304,Evansville,Municipal Police,Natrona,Wyoming,2003.0,July,1.0,Murder or Manslaughter,...,White,NaN,Acquaintance,Blunt Object,0.0,0.0,FBI,Blunt Object,Known,True
465684,465685,WY01900,Sweetwater,Sheriff,Sweetwater,Wyoming,2003.0,January,1.0,Murder or Manslaughter,...,White,NaN,In-Law,Rifle,0.0,0.0,FBI,Firearm,Other,True
465685,465686,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2003.0,July,1.0,Murder or Manslaughter,...,White,NaN,NaN,Suffocation,0.0,0.0,FBI,Other,Unknown,True

In [90]:
df.columns

Index(['Record ID', 'Agency Code', 'Agency Name', 'Agency Type', 'City',
       'State', 'Year', 'Month', 'Incident', 'Crime Type', 'Crime Solved',
       'Victim Sex', 'Victim Age', 'Victim Race', 'Victim Ethnicity',
       'Perpetrator Sex', 'Perpetrator Age', 'Perpetrator Race',
       'Perpetrator Ethnicity', 'Relationship', 'Weapon', 'Victim Count',
       'Perpetrator Count', 'Record Source', 'Weapon_Group',
       'Relationship_Group', 'Perpetrator_Age_Available'],
      dtype='str')

In [104]:
print(df['Weapon_Group'].value_counts())
print()
print(df['Relationship_Group'].value_counts())
print()
print(df['Victim Sex'].value_counts())
print()
print(df['Perpetrator Sex'].value_counts())
print()
print("Year dtype: ",df['Year'].dtype)
df['Year'] = df['Year'].astype(int)
print("(Updated) Year dtype: ",df['Year'].dtype)
print()
print("Total incidents: ",df[['Year','Month','City','Incident']].drop_duplicates().shape[0])
print()
print("Repeated Incidents: ",df[['Year','Month','City','Incident']].duplicated().sum())

Weapon_Group
Firearm         302707
Sharp Object     73691
Blunt Object     50485
Unknown          21387
Other            17416
Name: count, dtype: int64

Relationship_Group
Unknown     184541
Known       123584
Stranger     72912
Partner      48224
Family       20802
Other        10329
Sibling       5294
Name: count, dtype: int64

Victim Sex
Male      358720
Female    106325
Name: count, dtype: int64

Perpetrator Sex
Male      290736
Female     37512
Name: count, dtype: int64

Year dtype:  int64
(Updated) Year dtype:  int64

Total incidents:  348338

Repeated Incidents:  117348

In [105]:
df.to_csv("cleaned_data.csv", index=False)